name: Render Quarto Document

on:
  push:
    branches: main

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("ggplot2", "rmarkdown", "knitr"))'

      - name: Render Quarto
        run: quarto render diamonds_test.qmd --output-dir=docs

      - name: Commit rendered HTML
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/
          git commit -m "Publish rendered Quarto doc to GitHub Pages"
          git push
